import random
class BonusCard():
    def __init__(self):
        self.rare = ["Ambitious Augmenter (SOS) 140", "Antiquities on the Loose (SOS) 7", "Applied Geometry (SOS) 172", "Ark of Hunger (SOS) 173", "Aziza, Mage Tower Captain (SOS) 174", "Berta, Wise Extrapolator (SOS) 175", "Blech, Loafing Pest (SOS) 176", "Cauldron of Essence (SOS) 179", "Choreographed Sparks (SOS) 111", "Colorstorm Stallion (SOS) 180", "Comforting Counsel (SOS) 143", "Conciliator's Duelist (SOS) 182", "Deathcap Glade (SOS) 253", "Dina's Guidance (SOS) 184", "Dreamroot Cascade (SOS) 254", "Erode (SOS) 15", "Exhibition Tidecaller (SOS) 48", "Fix What's Broken (SOS) 188", "Flashback (SOS) 115", "Geometer's Arthropod (SOS) 191", "Grave Researcher // Reanimate (SOS) 85", "Great Hall of the Biblioplex (SOS) 257", "Hardened Academic (SOS) 194", "Harmonized Trio // Brainstorm (SOS) 52", "Informed Inkwright (SOS) 20", "Jadzi, Steward of Fate // Oracle's Gift (SOS) 55", "Joined Researchers // Secret Rendezvous (SOS) 23", "Maelstrom Artisan // Rocket Volley (SOS) 122", "Magmablood Archaic (SOS) 123", "Mana Sculpt (SOS) 57", "Mind into Matter (SOS) 202", "Molten-Core Maestro (SOS) 125", "Moment of Reckoning (SOS) 205", "Moseo, Vein's New Dean (SOS) 91", "Nita, Forum Conciliator (SOS) 206", "Pensive Professor (SOS) 63", "Petrified Hamlet (SOS) 259", "Planar Engineering (SOS) 158", "Postmortem Professor (SOS) 93", "Pox Plague (SOS) 94", "Practiced Offense (SOS) 25", "Resonating Lute (SOS) 221", "Scheming Silvertongue // Sign in Blood (SOS) 99", "Shattered Sanctum (SOS) 260", "Skycoach Conductor // All Aboard (SOS) 67", "Slumbering Trudge (SOS) 160", "Splatter Technique (SOS) 231", "Steal the Show (SOS) 130", "Stirring Hopesinger (SOS) 35", "Stormcarved Coast (SOS) 263", "Sundown Pass (SOS) 264", "Suspend Aggression (SOS) 236", "Together as One (SOS) 4", "Tragedy Feaster (SOS) 102", "Traumatic Critique (SOS) 239", "Vastlands Scavenger // Bind to Life (SOS) 166", "Vicious Rivalry (SOS) 241", "Wildgrowth Archaic (SOS) 168", "Wisdom of Ages (SOS) 71", "Zaffai and the Tempests (SOS) 246"]
        self.mythic = ["Decorum Dissertation (SOS) 78", "Echocasting Symposium (SOS) 44", "Emeritus of Abundance // Regrowth (SOS) 145", "Emeritus of Conflict // Lightning Bolt (SOS) 113", "Emeritus of Ideation // Ancestral Recall (SOS) 45", "Emeritus of Truce // Swords to Plowshares (SOS) 13", "Emeritus of Woe // Demonic Tutor (SOS) 80", "Germination Practicum (SOS) 149", "Improvisation Capstone (SOS) 120", "Lorehold, the Historian (SOS) 201", "Mathemagics (SOS) 58", "Prismari, the Inspiration (SOS) 212", "Professor Dellian Fel (SOS) 214", "Quandrix, the Proof (SOS) 218", "Ral Zarek, Guest Lecturer (SOS) 97", "Restoration Seminar (SOS) 30", "Silverquill, the Disputant (SOS) 226", "The Dawning Archaic (SOS) 1", "Witherbloom, the Balancer (SOS) 245", "Withering Curse (SOS) 105"]
        self.mythic_rate = .125

    def get_bonus_card(self):
        if random.random() < self.mythic_rate:
            random.shuffle(self.mythic)
            return self.mythic.pop()
        else:
            random.shuffle(self.rare)
            return self.rare.pop()